# Generated by Django 3.1.3 on 2020-12-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ['-created_date']},
        ),
    ]
