# Generated by Django 3.1.3 on 2020-11-03 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='trusted_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
