# Generated by Django 3.1.2 on 2020-11-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_time_reported_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='joined_date',
            new_name='date_joined',
        ),
    ]
