# Generated by Django 3.1.2 on 2020-11-01 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201101_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_by', to=settings.AUTH_USER_MODEL, verbose_name='Inviteret af'),
        ),
        migrations.AddField(
            model_name='member',
            name='marked_spam',
            field=models.BooleanField(default=False),
        ),
    ]
